// flow-typed signature: 130016fe7ca5640872bcb9c225ec2b6b
// flow-typed version: <<STUB>>/eslint-plugin-gigwalk_v^1.1.1/flow_v0.32.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-gigwalk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-gigwalk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-gigwalk/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-gigwalk/lib/rules/require-valid-flow-file-annotation' {
  declare module.exports: any;
}

declare module 'eslint-plugin-gigwalk/src/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-gigwalk/src/rules/require-valid-flow-file-annotation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-gigwalk/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-gigwalk/lib/index'>;
}
declare module 'eslint-plugin-gigwalk/lib/rules/require-valid-flow-file-annotation.js' {
  declare module.exports: $Exports<'eslint-plugin-gigwalk/lib/rules/require-valid-flow-file-annotation'>;
}
declare module 'eslint-plugin-gigwalk/src/index.js' {
  declare module.exports: $Exports<'eslint-plugin-gigwalk/src/index'>;
}
declare module 'eslint-plugin-gigwalk/src/rules/require-valid-flow-file-annotation.js' {
  declare module.exports: $Exports<'eslint-plugin-gigwalk/src/rules/require-valid-flow-file-annotation'>;
}
